version: '4'

services:
  mysql:
    image: mysql:8.0
    container_name: order-mysql
#    restart: always
    environment:
#      MYSQL_DATABASE: orderdb
#      MYSQL_USER: suri
#      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
